language: php

php:
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

sudo: false

install: travis_retry composer install

script: composer ci

cache:
  directories:
    - $HOME/.composer/cache
